server:
  port: 8088
spring:
  application:
    name: notification-service
  profiles:
    active: @spring.profiles.active@

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

# Logging
logging:
  level:
    root: INFO
    web: OFF
    org.springframework: INFO
    org.apache: OFF
    kafka: OFF