server:
  port: 4953

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: # dieu huong request thong qua chi dinh tuong ung tren url
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<segment>.*), /$\{segment}
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<segment>.*), /product/$\{segment}
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /order/$\{segment}
        - id: inventory-service
          uri: http://localhost:8086
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/(?<segment>.*), /inventory/$\{segment}
        - id: mail-service
          uri: http://localhost:8087
          predicates:
            - Path=/mail/**
          filters:
            - RewritePath=/mail/(?<segment>.*), /mail/$\{segment}
        - id: chat-service
          uri: http://localhost:8090
          predicates:
            - Path=/chat/**
          filters:
            - RewritePath=/chat/(?<segment>.*), /chat/$\{segment}


management: # hien thi thong tin suc khoe cua service
  endpoints:
    web:
      exposure:
        include: '*'
